name = "notesview"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2024-12-19"

[env.production]
name = "notesview"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx"]

[env.production.build]
command = "npm run build"

[build.upload]
format = "modules"
